//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create_Reports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Create_Reports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Products.SKU, Products.Name, Products.Description, Products.Brand, Pricing.Price as Price, Stock.[Location] as [Location] From Products
        ///    JOIN Pricing ON Products.SKU = Pricing.SKU
        ///    JOIN Stock ON Products.SKU = Stock.SKU
        ///Where Stock.[Location] in (&apos;Subassembly&apos;, &apos;Finished Goods Storage&apos;) AND 
        ///    Products.Brand in (&apos;ACME Corporation&apos;, &apos;Inner City Bikes&apos;).
        /// </summary>
        internal static string Report_1 {
            get {
                return ResourceManager.GetString("Report_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH DiscountedProducts AS (
        ///  SELECT p.*,
        ///         CASE WHEN pr.Price &gt; @P0 THEN pr.Price * (1 - @P1/100.0) ELSE pr.Price END AS DiscountedPrice
        ///  FROM Products p
        ///  INNER JOIN Pricing pr ON p.SKU = pr.SKU
        ///)
        ///SELECT dp.StyleCode,
        ///       MIN(dp.DiscountedPrice) AS LowestPrice,
        ///       MAX(dp.DiscountedPrice) AS HighestPrice
        ///FROM DiscountedProducts dp
        ///INNER JOIN Products p ON dp.SKU = p.SKU
        ///GROUP BY dp.StyleCode;
        ///
        ///SELECT * from products 
        ///join pricing on pricing.sku=products.sku
        ///ORDER by StyleCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report_2 {
            get {
                return ResourceManager.GetString("Report_2", resourceCulture);
            }
        }
    }
}
